# Generated by Django 5.2.17 on 2026-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
