# Generated by Django 5.2.17 on 2026-09-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
