# Generated by Django 5.2.17 on 2026-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_car_image_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_choice',
            field=models.CharField(choices=[('SELF', 'I will drive'), ('OTHER', 'Someone else will drive')], default='SELF', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_licence_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_licence_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='licence_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='licence_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='licence_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='licence_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
