# Generated by Django 5.2.17 on 2026-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_driver_licence_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
