"""Real DriveGo fleet: Indian-market cars with photos of the actual model.

Photos are Wikipedia lead images served from Wikimedia Commons (CC BY / CC BY-SA;
credit the authors listed on each file page). Registration numbers are unique
WB-series plates so re-running ``seed_fleet`` updates cars instead of duplicating them.
"""

FLEET = [
    {"brand": 'Maruti Suzuki', "model": 'Swift', "category": 'Hatchback', "seats": 5, "transmission": 'Manual', "fuel_type": 'Petrol',
     "price_per_day": 1400, "registration_number": "WB02DG1001", "features": 'AC, Bluetooth audio, Rear parking sensors, 2 Airbags',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Suzuki_Swift_%282024%29_hybrid_DSC_6076.jpg/960px-Suzuki_Swift_%282024%29_hybrid_DSC_6076.jpg'},
    {"brand": 'Hyundai', "model": 'i20', "category": 'Hatchback', "seats": 5, "transmission": 'Manual', "fuel_type": 'Petrol',
     "price_per_day": 1600, "registration_number": "WB02DG1002", "features": 'AC, Touchscreen, Apple CarPlay, 6 Airbags',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Hyundai_i20_%28III%2C_Facelift%29_%E2%80%93_f_11102025.jpg/960px-Hyundai_i20_%28III%2C_Facelift%29_%E2%80%93_f_11102025.jpg'},
    {"brand": 'Tata', "model": 'Altroz', "category": 'Hatchback', "seats": 5, "transmission": 'Manual', "fuel_type": 'Diesel',
     "price_per_day": 1500, "registration_number": "WB02DG1003", "features": 'AC, Touchscreen, Cruise control, 5-star safety',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Tata_Altroz_front_20230617.jpg/960px-Tata_Altroz_front_20230617.jpg'},
    {"brand": 'Maruti Suzuki', "model": 'Baleno', "category": 'Hatchback', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 1700, "registration_number": "WB02DG1004", "features": 'AC, Head-up display, 360° camera, 6 Airbags',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/2017_Suzuki_Baleno_SZ3_Dualjet_1.2_Front.jpg/960px-2017_Suzuki_Baleno_SZ3_Dualjet_1.2_Front.jpg'},
    {"brand": 'Tata', "model": 'Punch', "category": 'SUV', "seats": 5, "transmission": 'Manual', "fuel_type": 'Petrol',
     "price_per_day": 1600, "registration_number": "WB02DG1005", "features": 'AC, High ground clearance, Touchscreen, 5-star safety',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/2021_Tata_Punch_Creative_%28India%29_front_view_01.png/960px-2021_Tata_Punch_Creative_%28India%29_front_view_01.png'},
    {"brand": 'Honda', "model": 'City', "category": 'Sedan', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 2400, "registration_number": "WB02DG1006", "features": 'AC, Sunroof, Lane watch camera, Cruise control',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Honda_City_1.5_i-VTEC_V_%28VIII%2C_Facelift%29_%E2%80%93_f_22032025.jpg/960px-Honda_City_1.5_i-VTEC_V_%28VIII%2C_Facelift%29_%E2%80%93_f_22032025.jpg'},
    {"brand": 'Maruti Suzuki', "model": 'Dzire', "category": 'Sedan', "seats": 5, "transmission": 'Manual', "fuel_type": 'Petrol',
     "price_per_day": 1700, "registration_number": "WB02DG1007", "features": 'AC, Sunroof, Wireless charging, 6 Airbags',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Suzuki_Dzire_II_1.2_GLX_Hybrid_Arctic_White_Pearl.jpg/960px-Suzuki_Dzire_II_1.2_GLX_Hybrid_Arctic_White_Pearl.jpg'},
    {"brand": 'Skoda', "model": 'Slavia', "category": 'Sedan', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 2800, "registration_number": "WB02DG1008", "features": 'AC, Ventilated seats, Sunroof, 6 Airbags',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/2021_%C5%A0koda_Slavia_1.5_TSI_Style_%28India%29_front_view.png/960px-2021_%C5%A0koda_Slavia_1.5_TSI_Style_%28India%29_front_view.png'},
    {"brand": 'Volkswagen', "model": 'Virtus', "category": 'Sedan', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 2900, "registration_number": "WB02DG1009", "features": 'AC, Digital cockpit, Sunroof, 6 Airbags',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/2022_Volkswagen_Virtus_1.5_GT_%28India%29_front_view_02.png/960px-2022_Volkswagen_Virtus_1.5_GT_%28India%29_front_view_02.png'},
    {"brand": 'Hyundai', "model": 'Creta', "category": 'SUV', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Diesel',
     "price_per_day": 3000, "registration_number": "WB02DG1010", "features": 'AC, Panoramic sunroof, Ventilated seats, ADAS',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/2024_Hyundai_Creta_1.5_MPi_SX%28O%29_%28India%29_front_view.png/960px-2024_Hyundai_Creta_1.5_MPi_SX%28O%29_%28India%29_front_view.png'},
    {"brand": 'Kia', "model": 'Seltos', "category": 'SUV', "seats": 5, "transmission": 'Manual', "fuel_type": 'Petrol',
     "price_per_day": 2900, "registration_number": "WB02DG1011", "features": 'AC, Bose audio, 360° camera, ADAS',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Kia_Seltos_SP2_PE_Snow_White_Pearl_%2817%29_%28cropped%29.jpg/960px-Kia_Seltos_SP2_PE_Snow_White_Pearl_%2817%29_%28cropped%29.jpg'},
    {"brand": 'Tata', "model": 'Nexon', "category": 'SUV', "seats": 5, "transmission": 'Manual', "fuel_type": 'Petrol',
     "price_per_day": 2200, "registration_number": "WB02DG1012", "features": 'AC, Touchscreen, Sunroof, 5-star safety',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Tata_Nexon_Blue_Dual_Tone.jpg/960px-Tata_Nexon_Blue_Dual_Tone.jpg'},
    {"brand": 'Maruti Suzuki', "model": 'Brezza', "category": 'SUV', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 2500, "registration_number": "WB02DG1013", "features": 'AC, Sunroof, Head-up display, 360° camera',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/2022_Maruti_Suzuki_Brezza_ZXi%2B_%28India%29_front_view_03.png/960px-2022_Maruti_Suzuki_Brezza_ZXi%2B_%28India%29_front_view_03.png'},
    {"brand": 'Hyundai', "model": 'Venue', "category": 'SUV', "seats": 5, "transmission": 'Manual', "fuel_type": 'Petrol',
     "price_per_day": 2100, "registration_number": "WB02DG1014", "features": 'AC, Sunroof, Connected car, 6 Airbags',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/2022_Hyundai_Venue_Preferred_in_Polar_White%2C_Front_Right%2C_09-12-2023.jpg/960px-2022_Hyundai_Venue_Preferred_in_Polar_White%2C_Front_Right%2C_09-12-2023.jpg'},
    {"brand": 'Kia', "model": 'Sonet', "category": 'SUV', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Diesel',
     "price_per_day": 2400, "registration_number": "WB02DG1015", "features": 'AC, Ventilated seats, Bose audio, ADAS',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Kia_Sonet_QY_FL_1.5_LX_Snow_White_Pearl.jpg/960px-Kia_Sonet_QY_FL_1.5_LX_Snow_White_Pearl.jpg'},
    {"brand": 'Maruti Suzuki', "model": 'Grand Vitara', "category": 'SUV', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 2800, "registration_number": "WB02DG1016", "features": 'AC, Strong hybrid, Panoramic sunroof, 360° camera',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/2022_Suzuki_Grand_Vitara_GX_Smart_Hybrid_%28Indonesia%29_front_view.jpg/960px-2022_Suzuki_Grand_Vitara_GX_Smart_Hybrid_%28Indonesia%29_front_view.jpg'},
    {"brand": 'Mahindra', "model": 'XUV700', "category": 'SUV', "seats": 7, "transmission": 'Automatic', "fuel_type": 'Diesel',
     "price_per_day": 4200, "registration_number": "WB02DG1017", "features": 'AC, 7 Seats, Panoramic sunroof, ADAS',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/2021_Mahindra_XUV700_2.2_AX7_%28India%29_front_view.png/960px-2021_Mahindra_XUV700_2.2_AX7_%28India%29_front_view.png'},
    {"brand": 'Mahindra', "model": 'Scorpio-N', "category": 'SUV', "seats": 7, "transmission": 'Manual', "fuel_type": 'Diesel',
     "price_per_day": 3800, "registration_number": "WB02DG1018", "features": 'AC, 7 Seats, Sunroof, 4x4 capable',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/2024_Mahindra_Scorpio_Z8L_front.jpg/960px-2024_Mahindra_Scorpio_Z8L_front.jpg'},
    {"brand": 'Toyota', "model": 'Innova Hycross', "category": 'SUV', "seats": 7, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 4500, "registration_number": "WB02DG1019", "features": 'AC, 7 Seats, Strong hybrid, Captain seats',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Toyota_Innova_Zenix_2.0_V_%28III%29_%E2%80%93_f_22032025.jpg/960px-Toyota_Innova_Zenix_2.0_V_%28III%29_%E2%80%93_f_22032025.jpg'},
    {"brand": 'Toyota', "model": 'Fortuner', "category": 'SUV', "seats": 7, "transmission": 'Automatic', "fuel_type": 'Diesel',
     "price_per_day": 6500, "registration_number": "WB02DG1020", "features": 'AC, 7 Seats, 4x4, Leather seats',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/2015_Toyota_Fortuner_%28New_Zealand%29.jpg/960px-2015_Toyota_Fortuner_%28New_Zealand%29.jpg'},
    {"brand": 'Mahindra', "model": 'Thar', "category": 'SUV', "seats": 4, "transmission": 'Manual', "fuel_type": 'Diesel',
     "price_per_day": 3500, "registration_number": "WB02DG1021", "features": 'AC, 4x4, Convertible top, Off-road ready',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Mahindra_Thar_SUV_in_%22Red_Rage%22_color_at_Ashiana_Brahmanda%2C_East_Singbhum_India_%28Ank_Kumar%2C_Infosys_limited%29_02_%28cropped%29.jpg/960px-Mahindra_Thar_SUV_in_%22Red_Rage%22_color_at_Ashiana_Brahmanda%2C_East_Singbhum_India_%28Ank_Kumar%2C_Infosys_limited%29_02_%28cropped%29.jpg'},
    {"brand": 'BMW', "model": '3 Series', "category": 'Luxury', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 9500, "registration_number": "WB02DG1022", "features": 'Leather seats, Sunroof, Harman Kardon audio, Ambient lighting',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/2019_BMW_318d_SE_Automatic_2.0_Front.jpg/960px-2019_BMW_318d_SE_Automatic_2.0_Front.jpg'},
    {"brand": 'Mercedes-Benz', "model": 'C-Class', "category": 'Luxury', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Diesel',
     "price_per_day": 10500, "registration_number": "WB02DG1023", "features": 'Leather seats, Panoramic sunroof, Burmester audio, Ambient lighting',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Mercedes-Benz_W206_IMG_5796.jpg/960px-Mercedes-Benz_W206_IMG_5796.jpg'},
    {"brand": 'Audi', "model": 'Q5', "category": 'Luxury', "seats": 5, "transmission": 'Automatic', "fuel_type": 'Petrol',
     "price_per_day": 12000, "registration_number": "WB02DG1024", "features": 'Leather seats, Quattro AWD, Panoramic sunroof, Virtual cockpit',
     "image_url": 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Audi_Q5_2.0_TDI_quattro_S_line_%28GU%29_%E2%80%93_f_13102025.jpg/960px-Audi_Q5_2.0_TDI_quattro_S_line_%28GU%29_%E2%80%93_f_13102025.jpg'},
]
