from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("help/", views.help_center, name="help"),
    path("terms/", views.terms, name="terms"),
    path("privacy/", views.privacy, name="privacy"),
    path("cars/", views.car_list, name="cars"),
    path("cars/<int:car_id>/", views.car_detail, name="car_detail"),
    path("cars/<int:car_id>/availability/", views.car_availability, name="car_availability"),
    path("booking/<int:car_id>/", views.booking_dates, name="booking_dates"),
    path("driver/<str:booking_id>/", views.driver, name="driver"),
    path("delivery/<str:booking_id>/", views.delivery, name="delivery"),
    path("summary/<str:booking_id>/", views.summary, name="summary"),
    path("payment/verify/", views.payment_verify, name="payment_verify"),
    path("payment/<str:booking_id>/", views.payment, name="payment"),
    path("confirmation/<str:booking_id>/", views.confirmation, name="confirmation"),
    path("bookings/<str:booking_id>/cancel/", views.cancel_booking, name="cancel_booking"),
    path("my-bookings/", views.my_bookings, name="my_bookings"),
    # Kept so old links still land somewhere: the profile lives on My Bookings now.
    path("profile/", RedirectView.as_view(url="/my-bookings/#profile", permanent=False), name="profile"),
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("auth/clerk-callback/", views.clerk_callback, name="clerk_callback"),
    path("dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("dashboard/drivers/", views.admin_drivers, name="admin_drivers"),
    path("dashboard/bookings/", views.admin_bookings, name="admin_bookings"),
    path("dashboard/customers/", views.admin_customers, name="admin_customers"),
    path("dashboard/customers/<int:customer_id>/role/", views.admin_set_role, name="admin_set_role"),
    path("dashboard/cars/", views.admin_cars, name="admin_cars"),
    path("dashboard/locations/", views.admin_locations, name="admin_locations"),
    path("dashboard/blocks/", views.admin_blocks, name="admin_blocks"),
    path("dashboard/demo-toggle/", views.admin_demo_toggle, name="admin_demo_toggle"),
    path("dashboard/bookings/<str:booking_id>/", views.admin_booking_detail, name="admin_booking_detail"),
    path("dashboard/bookings/<str:booking_id>/cancel/", views.admin_cancel_booking, name="admin_cancel_booking"),
    path("dashboard/bookings/<str:booking_id>/trip/<str:action>/", views.admin_trip_action, name="admin_trip_action"),
    path("dashboard/bookings/<str:booking_id>/note/", views.admin_set_note, name="admin_set_note"),
    path("dashboard/bookings/<str:booking_id>/licence/", views.admin_check_licence, name="admin_check_licence"),
    path("dashboard/cars/<int:car_id>/status/", views.admin_set_car_status, name="admin_set_car_status"),
    path("dashboard/cars/add/", views.admin_add_car, name="admin_add_car"),
    path("dashboard/cars/<int:car_id>/edit/", views.admin_edit_car, name="admin_edit_car"),
    path("dashboard/locations/<int:location_id>/toggle/", views.admin_toggle_location, name="admin_toggle_location"),
    path("dashboard/blocks/<int:block_id>/delete/", views.admin_delete_block, name="admin_delete_block"),
    path("dashboard/locations/add/", views.admin_add_location, name="admin_add_location"),
    path("dashboard/blocks/add/", views.admin_block_dates, name="admin_block_dates"),
]
